# Generated by Django 3.2.7 on 2021-09-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50, verbose_name='Address (direccion)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel', models.CharField(max_length=10)),
            ],
        ),
    ]
